add multi-arch Dockerfiles and try some rare builds

diff --git a/docker/Dockerfile.alpine b/docker/Dockerfile.alpine
--- a/docker/Dockerfile.alpine
+++ b/docker/Dockerfile.alpine
@@ -1,20 +1,44 @@
 ARG ARCH=
 FROM alpine:3.19 as builder
 ARG TARGETARCH
+ARG TARGETVARIANT
 ARG VERSION=0.0.8
 
 RUN if [ "$TARGETARCH" = "amd64" ]; then \
         BIN_ARCH="x86_64"; \
+        BIN_FILE=pact_cli-${BIN_ARCH}-linux-musl; \
+    elif [ "$TARGETARCH" = "386" ] || [ "$TARGETARCH" = "586" ] || [ "$TARGETARCH" = "686" ]; then \
+        echo "Invalid TARGETVARIANT: ${TARGETVARIANT}"; \
+        exit 1; \
     elif [ "$TARGETARCH" = "arm64" ]; then \
         BIN_ARCH="aarch64"; \
+        BIN_FILE=pact_cli-${BIN_ARCH}-linux-musl; \
+    elif [ "$TARGETARCH" = "arm" ]; then \
+        echo ${TARGETVARIANT}; \
+        if [ "$TARGETVARIANT" = "v8" ]; then \
+            BIN_ARCH="arm"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabi; \
+        elif [ "$TARGETVARIANT" = "v7" ]; then \
+            BIN_ARCH="armv7"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabi; \
+        elif [ "$TARGETVARIANT" = "v6" ]; then \
+            BIN_ARCH="arm"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabihf; \
+        elif [ "$TARGETVARIANT" = "v5" ]; then \
+            BIN_ARCH="armv5te"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabihf; \
+        else \
+            echo "Invalid TARGETVARIANT: ${TARGETVARIANT}"; \
+            exit 1; \
+        fi; \
     else \
-        echo "Invalid TARGET_ARCH"; \
+        echo "Invalid TARGETARCH: ${TARGETARCH}"; \
         exit 1; \
     fi \
-    && wget -O pact_cli https://github.com/you54f/hello_cli/releases/download/v${VERSION}/pact_cli-${BIN_ARCH}-linux-musl && \
+    && wget -O pact_cli https://github.com/you54f/hello_cli/releases/download/v${VERSION}/${BIN_FILE} && \
     chmod +x pact_cli
 
-FROM --platform=linux/${TARGETARCH} alpine:3.19
+FROM --platform=linux/${TARGETARCH}${TARGETVARIANT:+/${TARGETVARIANT}} alpine:3.19
 WORKDIR /app
 COPY --from=builder /pact_cli /app/
 EXPOSE 8080
diff --git a/docker/Dockerfile.debian b/docker/Dockerfile.debian
--- a/docker/Dockerfile.debian
+++ b/docker/Dockerfile.debian
@@ -1,18 +1,42 @@
 ARG ARCH=
 FROM debian:11-slim as builder
 ARG TARGETARCH
+ARG TARGETVARIANT
 ARG VERSION=0.0.8
 
 RUN apt-get update && apt-get install -y wget
 RUN if [ "$TARGETARCH" = "amd64" ]; then \
         BIN_ARCH="x86_64"; \
+        BIN_FILE=pact_cli-${BIN_ARCH}-linux-musl; \
+    elif [ "$TARGETARCH" = "386" ] || [ "$TARGETARCH" = "586" ] || [ "$TARGETARCH" = "686" ]; then \
+        BIN_ARCH="i686"; \
+        BIN_FILE=pact_cli-${BIN_ARCH}-linux-gnu; \
     elif [ "$TARGETARCH" = "arm64" ]; then \
         BIN_ARCH="aarch64"; \
+        BIN_FILE=pact_cli-${BIN_ARCH}-linux-musl; \
+    elif [ "$TARGETARCH" = "arm" ]; then \
+        echo ${TARGETVARIANT}; \
+        if [ "$TARGETVARIANT" = "v8" ]; then \
+            BIN_ARCH="arm"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabi; \
+        elif [ "$TARGETVARIANT" = "v7" ]; then \
+            BIN_ARCH="armv7"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabi; \
+        elif [ "$TARGETVARIANT" = "v6" ]; then \
+            BIN_ARCH="arm"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabihf; \
+        elif [ "$TARGETVARIANT" = "v5" ]; then \
+            BIN_ARCH="armv5te"; \
+            BIN_FILE=pact_cli-${BIN_ARCH}-linux-musleabihf; \
+        else \
+            echo "Invalid TARGETVARIANT: ${TARGETVARIANT}"; \
+            exit 1; \
+        fi; \
     else \
-        echo "Invalid TARGET_ARCH"; \
+        echo "Invalid TARGETARCH: ${TARGETARCH}"; \
         exit 1; \
     fi \
-    && wget -O pact_cli https://github.com/you54f/hello_cli/releases/download/v${VERSION}/pact_cli-${BIN_ARCH}-linux-musl && \
+    && wget -O pact_cli https://github.com/you54f/hello_cli/releases/download/v${VERSION}/${BIN_FILE} && \
     chmod +x pact_cli
 
 FROM --platform=linux/${TARGETARCH} debian:11-slim
